name: Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install "./server[dev]"
          pip install "./client[dev]"

      - name: Run server tests
        run: python -m pytest server/tests -v
      - name: Run client tests
        run: python -m pytest client/tests -v
